version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.3.0

    working_directory: ~/laravel

    steps:
      - checkout
      - run:
          name: Setup Laravel
          command: |
            sudo apt-get update && sudo apt-get install -y unzip
            composer install
            cp .env.example .env
            php artisan key:generate

      - run:
          name: Run Tests
          command: php artisan test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - '*'
