version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.3-node-browsers

    working_directory: ~/laravel

    steps:
      - checkout

      # Setup Laravel environment
      - run:
          name: Setup Laravel
          command: |
            sudo apt-get update && sudo apt-get install -y unzip
            composer install
            cp .env.example .env
            php artisan key:generate

      # Run tests
      - run:
          name: Run Tests
          command: php artisan test
